
server:
  port: 8080

spring:
  data:
    mongodb:
      host: ${IP_ADDRESS}
      port: 27017
      username: ${USERNAME}
      password: ${PASSWORD}
      database: hotelizeDB


jwt:
  secretKey: ${secretKey}
  audience: ${audience}
  issuer:   ${issuer}
